// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IApi is an autogenerated mock type for the IApi type
type IApi struct {
	mock.Mock
}

// NewIApi creates a new instance of IApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *IApi {
	mock := &IApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
