// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewIRedisClient creates a new instance of IRedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRedisClient {
	mock := &IRedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IRedisClient is an autogenerated mock type for the IRedisClient type
type IRedisClient struct {
	mock.Mock
}

type IRedisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *IRedisClient) EXPECT() *IRedisClient_Expecter {
	return &IRedisClient_Expecter{mock: &_m.Mock}
}
