// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IRedisClient is an autogenerated mock type for the IRedisClient type
type IRedisClient struct {
	mock.Mock
}

// NewIRedisClient creates a new instance of IRedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRedisClient {
	mock := &IRedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
