// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Itask is an autogenerated mock type for the Itask type
type Itask struct {
	mock.Mock
}

// NewItask creates a new instance of Itask. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItask(t interface {
	mock.TestingT
	Cleanup(func())
}) *Itask {
	mock := &Itask{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
