// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package api

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIApi creates a new instance of MockIApi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIApi(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIApi {
	mock := &MockIApi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIApi is an autogenerated mock type for the IApi type
type MockIApi struct {
	mock.Mock
}

type MockIApi_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIApi) EXPECT() *MockIApi_Expecter {
	return &MockIApi_Expecter{mock: &_m.Mock}
}
