// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package TaskQueue

import (
	"github.com/hibiken/asynq"
	mock "github.com/stretchr/testify/mock"
)

// NewMockItask creates a new instance of MockItask. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItask(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItask {
	mock := &MockItask{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItask is an autogenerated mock type for the Itask type
type MockItask struct {
	mock.Mock
}

type MockItask_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItask) EXPECT() *MockItask_Expecter {
	return &MockItask_Expecter{mock: &_m.Mock}
}

// Payload provides a mock function for the type MockItask
func (_mock *MockItask) Payload() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payload")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockItask_Payload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payload'
type MockItask_Payload_Call struct {
	*mock.Call
}

// Payload is a helper method to define mock.On call
func (_e *MockItask_Expecter) Payload() *MockItask_Payload_Call {
	return &MockItask_Payload_Call{Call: _e.mock.On("Payload")}
}

func (_c *MockItask_Payload_Call) Run(run func()) *MockItask_Payload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockItask_Payload_Call) Return(bytes []byte) *MockItask_Payload_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockItask_Payload_Call) RunAndReturn(run func() []byte) *MockItask_Payload_Call {
	_c.Call.Return(run)
	return _c
}

// ResultWriter provides a mock function for the type MockItask
func (_mock *MockItask) ResultWriter() *asynq.ResultWriter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResultWriter")
	}

	var r0 *asynq.ResultWriter
	if returnFunc, ok := ret.Get(0).(func() *asynq.ResultWriter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*asynq.ResultWriter)
		}
	}
	return r0
}

// MockItask_ResultWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResultWriter'
type MockItask_ResultWriter_Call struct {
	*mock.Call
}

// ResultWriter is a helper method to define mock.On call
func (_e *MockItask_Expecter) ResultWriter() *MockItask_ResultWriter_Call {
	return &MockItask_ResultWriter_Call{Call: _e.mock.On("ResultWriter")}
}

func (_c *MockItask_ResultWriter_Call) Run(run func()) *MockItask_ResultWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockItask_ResultWriter_Call) Return(resultWriter *asynq.ResultWriter) *MockItask_ResultWriter_Call {
	_c.Call.Return(resultWriter)
	return _c
}

func (_c *MockItask_ResultWriter_Call) RunAndReturn(run func() *asynq.ResultWriter) *MockItask_ResultWriter_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockItask
func (_mock *MockItask) Type() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockItask_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockItask_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockItask_Expecter) Type() *MockItask_Type_Call {
	return &MockItask_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockItask_Type_Call) Run(run func()) *MockItask_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockItask_Type_Call) Return(s string) *MockItask_Type_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockItask_Type_Call) RunAndReturn(run func() string) *MockItask_Type_Call {
	_c.Call.Return(run)
	return _c
}
