// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package redisclient

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIRedisClient creates a new instance of MockIRedisClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRedisClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRedisClient {
	mock := &MockIRedisClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRedisClient is an autogenerated mock type for the IRedisClient type
type MockIRedisClient struct {
	mock.Mock
}

type MockIRedisClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRedisClient) EXPECT() *MockIRedisClient_Expecter {
	return &MockIRedisClient_Expecter{mock: &_m.Mock}
}
